// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VejBookASP.Database;

namespace VejBookASP.Database.Migrations.Migrations
{
    [DbContext(typeof(VejBookContext))]
    [Migration("20200930174237_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VejBookASP.Domain.Model.BCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BCalendars");
                });

            modelBuilder.Entity("VejBookASP.Domain.Model.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("VejBookASP.Domain.Model.Hold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BCalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentLastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeacherLastName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BCalendarId");

                    b.HasIndex("StudentLastName");

                    b.HasIndex("TeacherLastName");

                    b.ToTable("Holds");
                });

            modelBuilder.Entity("VejBookASP.Domain.Model.Student", b =>
                {
                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LastName");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("VejBookASP.Domain.Model.Teacher", b =>
                {
                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LastName");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("VejBookASP.Domain.Model.Timeslot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Timeslots");
                });

            modelBuilder.Entity("VejBookASP.Domain.Model.Hold", b =>
                {
                    b.HasOne("VejBookASP.Domain.Model.BCalendar", null)
                        .WithMany("Holds")
                        .HasForeignKey("BCalendarId");

                    b.HasOne("VejBookASP.Domain.Model.Student", null)
                        .WithMany("Holds")
                        .HasForeignKey("StudentLastName");

                    b.HasOne("VejBookASP.Domain.Model.Teacher", null)
                        .WithMany("Holds")
                        .HasForeignKey("TeacherLastName");
                });
#pragma warning restore 612, 618
        }
    }
}
